version: "3"
services:
  drone-server:
    container_name: drone-server
    image: drone/drone
    restart: always
    ports:
      - 80:80
    volumes:
      - db-data:/var/lib/drone/
    environment:
      - DRONE_DEBUG=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${RELAY_HOST}
      - DRONE_SERVER_PROTO=http
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_USER_CREATE=username:${DRONE_ADMIN},admin:true
    network_mode: bridge

  drone-agent:
    container_name: drone-agent
    image: drone/agent
    restart: always
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=${RELAY_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME="local"
    depends_on:
      - drone-server

volumes:
  db-data:
